
cloudinary:
  cloud-name: ddk8osgyk
  api-key: 848718324627338
  api-secret: IlW5Xc70JZOIqM9gOdNo13JkpWM
  secure: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Sirve el frontend
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/, file:frontend/

jwt:
  secret: ${JWT_SECRET}
