cloudinary:
  cloud-name: ddk8osgyk
  api-key: 848718324627338
  api-secret: IlW5Xc70JZOIqM9gOdNo13JkpWM
  secure: true

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/bdreposteria?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true  
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${PORT:8080}
  address: 0.0.0.0
